[package]
name = "specjam"
version = "0.0.2"
edition = "2021"
description = "A tool which can spawn a binary runner to test the JAM spec"
license = "GPL-3.0"
documentation = "https://docs.rs/specjam"
repository = "https://github.com/spacejam-network/specjam"
homepage = "https://github.com/spacejam-network/specjam"
exclude = ["jamtestvectors"]

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5", features = ["derive"] }
colored = "3.0.0"
serde_json = "1.0.135"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

[build-dependencies]
anyhow = "1.0.95"
heck = "0.5.0"
hex = "0.4.3"
paste = "1.0.15"
proc-macro2 = "1.0.92"
quote = "1.0.38"
serde_json = "1.0.135"
syn = "2.0.95"
