[package]
name = "specjam"
version = "0.0.1"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5", features = ["derive"] }
colored = "3.0.0"
serde = "1.0.217"
serde_json = "1.0.135"
tempfile = "3.15.0"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

[build-dependencies]
anyhow = "1.0.95"
git2 = "0.20.0"
proc-macro2 = "1.0.92"
quote = "1.0.38"
syn = "2.0.95"
